# Generated by Django 3.2 on 2021-05-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FmeaRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=200)),
                ('preparedBy', models.CharField(max_length=200)),
                ('responsible', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('revisedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FmeaProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processStep', models.CharField(max_length=300)),
                ('potentialFaliureMode', models.CharField(max_length=300)),
                ('potentialFailureEffect', models.CharField(max_length=300)),
                ('severity', models.IntegerField(default=0)),
                ('potentialCause', models.CharField(max_length=300)),
                ('occurence', models.IntegerField(default=0)),
                ('currentControls', models.CharField(max_length=300)),
                ('detection', models.IntegerField(default=0)),
                ('rpn', models.IntegerField(default=0)),
                ('actionRecommended', models.CharField(max_length=300)),
                ('responsiblePerson', models.CharField(max_length=200)),
                ('actionTaken', models.CharField(max_length=300)),
                ('fmeaRegister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmea_form.fmearegister')),
            ],
        ),
    ]
