# Generated by Django 3.2 on 2021-09-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmeaprocess',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
