# Generated by Django 3.2 on 2021-09-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_form', '0002_fmeaprocess_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmeaprocess',
            old_name='type',
            new_name='processType',
        ),
    ]
