# Generated by Django 3.2 on 2021-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_form', '0003_rename_type_fmeaprocess_processtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmeaprocess',
            name='occurence',
            field=models.IntegerField(choices=[('10', 'More than once per day'), ('9', 'Once every 3-4 days'), ('8', 'Once Every week')], default=0),
        ),
    ]
