# Generated by Django 3.2 on 2021-09-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_form', '0006_alter_fmeaprocess_occurence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmeaprocess',
            name='rpn',
        ),
    ]
