# Generated by Django 3.2 on 2021-09-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_form', '0007_remove_fmeaprocess_rpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmeaprocess',
            name='finalDetection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fmeaprocess',
            name='finalOccurence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fmeaprocess',
            name='finalSeverity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fmeaprocess',
            name='reference',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='fmeaprocess',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='actionRecommended',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='actionTaken',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='currentControls',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='occurence',
            field=models.IntegerField(choices=[(10, 'More than once per day'), (9, 'Once every 3-4 days'), (8, 'Once Every week'), (7, 'Once every month'), (6, 'Once every 3 months'), (5, 'Once every 6 months'), (4, 'Once every 9 months'), (3, 'Twice a year'), (2, 'Once a Year'), (1, 'Once every 1 - 3 years')], default=0),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='potentialCause',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='potentialFailureEffect',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='potentialFaliureMode',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='processStep',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='fmeaprocess',
            name='processType',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
